name: pytorch_benchmarks
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates
  - certifi
  - cffi
  - cudatoolkit=10.1
  - freetype
  - intel-openmp
  - jpeg
  - libpng
  - libtiff
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pillow
  - pip
  - pycparser
  - python=3.7
  - python-dateutil
  - pytorch=1.3
  - pytz
  - setuptools
  - six
  - sqlite
  - tk
  - torchvision
  - wheel
  - xz
  - zlib
  - zstd

